### ISSUE TITLE
Generar documento PDF con la memoria de la práctica

### ISSUE THREAD

**Issue by pablo-campillo** [pablo-campillo/brand_car_scraper#13]

**Comment by pucedam** [comment]
Comienzo el documento en libreofficeword, ya qye estoy trabajando desde Ubuntu

**Comment by pablo-campillo** [comment]
Se me ha olvidado referenciar la tarea en el commit, pero creo que ya está la memoria terminada. :-)

**Comment by pucedam** [comment]
Cierro la tarea, la damos por terminada, sí :)
