### ISSUE TITLE
Definir características a extraer

### ISSUE THREAD

**Issue by pablo-campillo** [pablo-campillo/brand_car_scraper#3]
Definir las características a extraer y la ruta clave en el html.

**Comment by pucedam** [comment]
Comienzo esta tarea

**Comment by pucedam** [comment]
@pablo-campillo , he incorporado en el commit adjunto una petición simple de la página añadiendo la región donde se quieren consultar los coches.

He supuesto lo siguiente: 
- Que consultamos por fecha
- Que tenemos en cuenta la región para ser capaces luego de guardar facilmente la región de los vehículos
- Para cada vehículo: Marca, modelo, 1 foto, precio, tipo de vendedor, kilometraje, año, transmisión manual o automática , numero de puertas y potencia.

**Comment by pablo-campillo** [comment]
También pondría:
- Descripción
- Identificador: para poder identificar anuncios repetidos
- Fijarse que sean OFERTA y no DEMANDA
- Timestamp de cuando ha sido scrapeado
- Antiguedad del anuncio (días, horas, DESTACADO, NUEVO ANUNCIO).

**Comment by pucedam** [comment]
Genial, cerramos entonces, teniendo en cuenta que filtramos por solo OFERTA
