### ISSUE TITLE
Crear representación gráfica de los datos.

### ISSUE THREAD

**Issue by pablo-campillo** [pablo-campillo/brand_car_scraper#4]

**Comment by pablo-campillo** [comment]
He creado una imagen que representa un registro de anuncio de coche con sus atributos:

![features](https://user-images.githubusercontent.com/65536570/97856792-146e2b00-1cfd-11eb-9c0f-3104e6d48aff.png)

**Comment by pablo-campillo** [comment]
@pucedam te parece bien? Podríamos además incluir un ejemplo de unas cuantos registros.

**Comment by pucedam** [comment]
Está guay. De todos modos, viendo la imagen en el ejemplo aportado en https://github.com/tteguayco/Web-scraping-aviation-accidents/blob/master/pdf/respuestas.pdf, estamos seguros de que tiene que ser algo así?

**Comment by pablo-campillo** [comment]
Podemos poner en el centro del círculo una imagen como esta:

[For sale](https://img.autobytel.com/car-reviews/autobytel/-pros-and-cons-of-buying-a-certified-pre-owned-used-car/ABTL_Private_party_used_car_sale_bigstock.jpg)

**Comment by pucedam** [comment]
vale, por mi genial :) Otra cosa, los atributos los  dejamos en inglés o en castellano? Lo digo porque por ejemplo el Readme lo tenemos que cambiar al castellano como  nos indicó el profesor.

**Comment by pucedam** [comment]
![features](https://user-images.githubusercontent.com/66958046/98153934-3ec61100-1ed4-11eb-9157-8c876649f1cb.png)

Actualizo la imagen con la foto de for sale y dejo en inglés los atributos. Cierro issue.
