### ISSUE TITLE
Parsear todos los anuncios de una página

### ISSUE THREAD

**Issue by pablo-campillo** [pablo-campillo/brand_car_scraper#6]
parsear todos los anuncios de una página dada y guardarlos en el csv

**Comment by pablo-campillo** [comment]
De la issue #5 me he dado cuenta que sólo obtiene 2 anuncios (2 artículos). Habrá que ver qué hace falta para obtener todos los anuncios (selenium y hacer scroll? mandar session? cookies?)

**Comment by pucedam** [comment]
Hacemos aquí el cambio para procesar esos dos anuncios y lo vemos en la issue #8 , cambiando las credenciales.
